---@meta

---@class FAnimBlueprintGeneratedConstantData : FAnimBlueprintConstantData
---@field __NameProperty_1320 FName
---@field __NameProperty_1321 FName
---@field __NameProperty_1322 FName
---@field __NameProperty_1323 FName
---@field __NameProperty_1324 FName
---@field __NameProperty_1325 FName
---@field __NameProperty_1326 FName
---@field __ArrayProperty_1327 TArray<float>
---@field __EnumProperty_1328 EAlphaBlendOption
---@field __ArrayProperty_1329 TArray<float>
---@field __ByteProperty_1330 ERefPoseType
---@field __ArrayProperty_1331 TArray<float>
---@field __NameProperty_1332 FName
---@field __NameProperty_1333 FName
---@field __IntProperty_1334 int32
---@field __NameProperty_1335 FName
---@field __IntProperty_1336 int32
---@field __NameProperty_1337 FName
---@field __IntProperty_1338 int32
---@field __NameProperty_1339 FName
---@field __IntProperty_1340 int32
---@field __NameProperty_1341 FName
---@field __IntProperty_1342 int32
---@field __NameProperty_1343 FName
---@field __IntProperty_1344 int32
---@field __NameProperty_1345 FName
---@field __IntProperty_1346 int32
---@field __NameProperty_1347 FName
---@field __IntProperty_1348 int32
---@field __NameProperty_1349 FName
---@field __IntProperty_1350 int32
---@field __NameProperty_1351 FName
---@field __IntProperty_1352 int32
---@field __NameProperty_1353 FName
---@field __IntProperty_1354 int32
---@field __BlendProfile_1355 UBlendProfile
---@field __CurveFloat_1356 UCurveFloat
---@field __EnumProperty_1357 EAlphaBlendOption
---@field __EnumProperty_1358 EBlendListTransitionType
---@field __ArrayProperty_1359 TArray<float>
---@field __BoolProperty_1360 boolean
---@field __FloatProperty_1361 float
---@field __StructProperty_1362 FInputScaleBiasClampConstants
---@field __FloatProperty_1363 float
---@field __BoolProperty_1364 boolean
---@field __EnumProperty_1365 EAnimSyncMethod
---@field __ByteProperty_1366 EAnimGroupRole::Type
---@field __NameProperty_1367 FName
---@field __NameProperty_1368 FName
---@field __IntProperty_1369 int32
---@field __StructProperty_1370 FAnimNodeFunctionRef
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystem_PropertyAccess
---@field AnimBlueprintExtension_Base FAnimSubsystem_Base
FAnimBlueprintGeneratedConstantData = {}



---@class FAnimBlueprintGeneratedMutableData : FAnimBlueprintMutableData
---@field __BoolProperty boolean
---@field __BoolProperty_0 boolean
---@field __ArrayProperty_1 TArray<float>
---@field __BoolProperty_2 boolean
---@field __BoolProperty_3 boolean
---@field __BoolProperty_4 boolean
---@field __BoolProperty_5 boolean
---@field __FloatProperty_6 float
---@field __FloatProperty_7 float
---@field __BoolProperty_8 boolean
---@field __BoolProperty_9 boolean
---@field __BoolProperty_10 boolean
---@field __BoolProperty_11 boolean
---@field __FloatProperty_12 float
---@field __FloatProperty_13 float
---@field __FloatProperty_14 float
---@field __FloatProperty_15 float
---@field __BoolProperty_16 boolean
---@field __BoolProperty_17 boolean
---@field __BoolProperty_18 boolean
---@field __BoolProperty_19 boolean
---@field __ArrayProperty_20 TArray<float>
---@field __BoolProperty_21 boolean
---@field __BoolProperty_22 boolean
---@field __BoolProperty_23 boolean
---@field __BoolProperty_24 boolean
---@field __ArrayProperty_25 TArray<float>
---@field __BoolProperty_26 boolean
---@field __BoolProperty_27 boolean
---@field __BoolProperty_28 boolean
---@field __FloatProperty_29 float
---@field __FloatProperty_30 float
---@field __FloatProperty_31 float
---@field __FloatProperty_32 float
---@field __BoolProperty_33 boolean
---@field __FloatProperty_34 float
---@field __FloatProperty_35 float
---@field __BoolProperty_36 boolean
---@field __FloatProperty_37 float
---@field __BoolProperty_38 boolean
---@field __BoolProperty_39 boolean
---@field __FloatProperty_40 float
---@field __FloatProperty_41 float
---@field __FloatProperty_42 float
---@field __FloatProperty_43 float
---@field __FloatProperty_44 float
---@field __FloatProperty_45 float
---@field __FloatProperty_46 float
---@field __FloatProperty_47 float
---@field __FloatProperty_48 float
---@field __FloatProperty_49 float
---@field __BoolProperty_50 boolean
---@field __BoolProperty_51 boolean
---@field __BoolProperty_52 boolean
---@field __BoolProperty_53 boolean
FAnimBlueprintGeneratedMutableData = {}



---@class UABP_Player_C : UPalAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field __AnimBlueprintMutables FAnimBlueprintGeneratedMutableData
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystemInstance
---@field AnimBlueprintExtension_Base FAnimSubsystemInstance
---@field AnimGraphNode_Root_7 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_6 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_6 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_5 FAnimNode_LinkedInputPose
---@field AnimGraphNode_ComponentToLocalSpace_6 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_6 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SaveCachedPose_16 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_28 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_41 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_40 FAnimNode_UseCachedPose
---@field AnimGraphNode_Fabrik FAnimNode_Fabrik
---@field AnimGraphNode_Root_5 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_4 FAnimNode_LinkedInputPose
---@field AnimGraphNode_ModifyBone_18 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_5 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_17 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_16 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_15 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_14 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_13 FAnimNode_ModifyBone
---@field AnimGraphNode_TwoBoneIK_5 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_4 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_3 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_2 FAnimNode_TwoBoneIK
---@field AnimGraphNode_SaveCachedPose_15 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_39 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_27 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_38 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_5 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_Root_4 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_3 FAnimNode_LinkedInputPose
---@field AnimGraphNode_LookAt FAnimNode_LookAt
---@field AnimGraphNode_BlendListByBool_26 FAnimNode_BlendListByBool
---@field AnimGraphNode_ComponentToLocalSpace_4 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_14 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_37 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_36 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_4 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_Root_3 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_2 FAnimNode_LinkedInputPose
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_LocalToComponentSpace_3 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_3 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone_12 FAnimNode_ModifyBone
---@field AnimGraphNode_BlendListByBool_25 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_13 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_35 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_34 FAnimNode_UseCachedPose
---@field AnimGraphNode_Root_2 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_1 FAnimNode_LinkedInputPose
---@field AnimGraphNode_BlendListByBool_24 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_21 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_23 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_20 FAnimNode_SequencePlayer
---@field AnimGraphNode_Slot_14 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_12 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_9 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_33 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_32 FAnimNode_UseCachedPose
---@field AnimGraphNode_RotationOffsetBlendSpace_2 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_UseCachedPose_31 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_22 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_30 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_13 FAnimNode_Slot
---@field AnimGraphNode_Slot_12 FAnimNode_Slot
---@field AnimGraphNode_SequencePlayer_19 FAnimNode_SequencePlayer
---@field AnimGraphNode_Slot_11 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_29 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_2 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_11 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_10 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_9 FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace_2 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_Slot_10 FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool_21 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_28 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_8 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_9 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_11 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SequencePlayer_18 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_20 FAnimNode_BlendListByBool
---@field AnimGraphNode_ModifyBone_8 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_7 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_6 FAnimNode_ModifyBone
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_27 FAnimNode_UseCachedPose
---@field AnimGraphNode_TwoWayBlend_7 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_26 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_19 FAnimNode_BlendListByBool
---@field AnimGraphNode_Root_1 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_7 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_RotationOffsetBlendSpace_1 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_Slot_8 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_5 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_4 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_3 FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_18 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_17 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_16 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_15 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_25 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_14 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_24 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_13 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_23 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_22 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_7 FAnimNode_Slot
---@field AnimGraphNode_Slot_6 FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool_12 FAnimNode_BlendListByBool
---@field AnimGraphNode_LayeredBoneBlend_6 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_21 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_20 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_19 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_18 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_17 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_11 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_5 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_5 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_10 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_TwoWayBlend_6 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_17 FAnimNode_SequencePlayer
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_9 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_16 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_5 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_4 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_4 FAnimNode_Slot
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_IdentityPose FAnimNode_RefPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_4 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendListByBool_8 FAnimNode_BlendListByBool
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_BlendSpacePlayer_10 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_9 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_8 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_LocalRefPose FAnimNode_RefPose
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_7 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendSpacePlayer_7 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_6 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_TwoWayBlend_3 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendSpacePlayer_5 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_TwoWayBlend_2 FAnimNode_TwoWayBlend
---@field AnimGraphNode_TwoWayBlend_1 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_LinkedAnimLayer_6 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_5 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_4 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_3 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_2 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer_1 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_ControlRig FAnimNode_ControlRig
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field K2Node_PropertyAccess_36 float
---@field K2Node_PropertyAccess_34 boolean
---@field K2Node_PropertyAccess_31 FRotator
---@field K2Node_PropertyAccess_30 float
---@field K2Node_PropertyAccess_29 float
---@field K2Node_PropertyAccess_28 FVector
---@field K2Node_PropertyAccess_27 boolean
---@field K2Node_PropertyAccess_25 FRotator
---@field K2Node_PropertyAccess_24 FVector
---@field K2Node_PropertyAccess_23 FVector
---@field K2Node_PropertyAccess_22 FVector
---@field K2Node_PropertyAccess_21 boolean
---@field K2Node_PropertyAccess_20 boolean
---@field K2Node_PropertyAccess_19 boolean
---@field K2Node_PropertyAccess_18 boolean
---@field K2Node_PropertyAccess_17 boolean
---@field K2Node_PropertyAccess_16 boolean
---@field K2Node_PropertyAccess_15 EPalCharacterMovementCustomMode
---@field K2Node_PropertyAccess_14 FVector
---@field K2Node_PropertyAccess_13 FTransform
---@field K2Node_PropertyAccess_12 boolean
---@field K2Node_PropertyAccess_11 APalWeaponBase
---@field K2Node_PropertyAccess_10 boolean
---@field K2Node_PropertyAccess_9 boolean
---@field K2Node_PropertyAccess_8 APalWeaponBase
---@field K2Node_PropertyAccess_7 boolean
---@field K2Node_PropertyAccess_6 boolean
---@field K2Node_PropertyAccess_5 boolean
---@field K2Node_PropertyAccess_4 boolean
---@field K2Node_PropertyAccess_3 FRidingAnimationInfo
---@field K2Node_PropertyAccess_2 float
---@field K2Node_PropertyAccess_1 FWeaponAnimationInfo
---@field K2Node_PropertyAccess FWeaponAnimationInfo
---@field __CustomProperty_ClavicleAdjustFloat_3EAAD7D248100B118DCFE280A191AF83 float
---@field Speed double
---@field IsAim boolean
---@field VelocityXY FVector2D
---@field IsGliding boolean
---@field AimRotatorForSpine FRotator
---@field IsShooting boolean
---@field AimRotatorArm FRotator
---@field IsRiding boolean
---@field WeaponInfo FWeaponAnimationInfo
---@field PrevWeaponInfo FWeaponAnimationInfo
---@field ChangeWeaponWeight double
---@field Right double
---@field Forward double
---@field Pitch double
---@field Yaw double
---@field isCrouch boolean
---@field isAttachLeftHand boolean
---@field IsSliding boolean
---@field IsRequestSliding boolean
---@field IsEnableSkySliding boolean
---@field IsSprint boolean
---@field RidingAnimationInfo FRidingAnimationInfo
---@field HasWeapon boolean
---@field KawaiiWeight double
---@field Cloth01_FrontBagRotator FRotator
---@field IsReloading boolean
---@field IsJumpPreliminary boolean
---@field IsEndJump boolean
---@field LeftHandTransform FTransform
---@field IsValidSprintAnimation boolean
---@field RidingActor AActor
---@field RiderModelIsBackward boolean
---@field UseRidingAO boolean
---@field AimRotatorForSpine_Ride_WS FRotator
---@field IsDead boolean
---@field FootIKEnable boolean
---@field IsLookatEnable boolean
---@field LookAtTarget FVector
---@field LookatInTime double
---@field LookatOutTime double
---@field IsClimbing boolean
---@field UniqueRideAnim UAnimSequence
---@field IsUniqueRiding boolean
---@field Ride_IKPosHandR FVector
---@field Ride_IKPosHandL FVector
---@field Ride_IKPosFootR FVector
---@field Ride_IKPosFootL FVector
---@field Ride_SpineAddRotate FRotator
---@field Ride_HipForwardAdd double
---@field Ride_SpineWeight double
---@field UniqueRide_RightHandWeight double
---@field RideIK_Pole_HandR FVector
---@field RideIK_Pole_HandL FVector
---@field RideIK_Pole_FootR FVector
---@field RideIK_Pole_FootL FVector
---@field IsUniqueRideIK boolean
---@field UniqueRide_LeftHandWeight double
---@field FootStepEffect UNiagaraComponent
---@field IsWalking boolean
---@field ClavicleAdjustDegree float
---@field GlidingAS UAnimSequence
---@field BlendTime_ForEagleGlider double
---@field IsDedicatedServer boolean
---@field TSCached_OwnerCharacter APalCharacter
---@field TSCached_ShooterComponent UPalShooterComponent
---@field TSCached_MovementComponent UPalCharacterMovementComponent
---@field TSCached_LookAtComponent UPalLookAtComponent
---@field TSCached_FootIkComponent UPalFootIKComponent
---@field TSCached_SkeletalMeshComponent UPalSkeletalMeshComponent
---@field TSCache_CameraRotator FRotator
UABP_Player_C = {}

---@param InPose FPoseLink
---@param ClothLayer FPoseLink
function UABP_Player_C:ClothLayer(InPose, ClothLayer) end
---@param InPose FPoseLink
---@param LeftHandAttach FPoseLink
function UABP_Player_C:LeftHandAttach(InPose, LeftHandAttach) end
---@param InPose_3 FPoseLink
---@param UniqueRideFullBodyIK FPoseLink
function UABP_Player_C:UniqueRideFullBodyIK(InPose_3, UniqueRideFullBodyIK) end
---@param InPose_2 FPoseLink
---@param Lookat FPoseLink
function UABP_Player_C:Lookat(InPose_2, Lookat) end
---@param InPose_1 FPoseLink
---@param FootIK FPoseLink
function UABP_Player_C:FootIK(InPose_1, FootIK) end
---@param InPose_0 FPoseLink
---@param RidingOverride FPoseLink
function UABP_Player_C:RidingOverride(InPose_0, RidingOverride) end
---@param InPose FPoseLink
---@param WeaponUpperOverride FPoseLink
function UABP_Player_C:WeaponUpperOverride(InPose, WeaponUpperOverride) end
---@param AnimGraph FPoseLink
function UABP_Player_C:AnimGraph(AnimGraph) end
function UABP_Player_C:TempFixLeftHandAttach() end
---@param DeltaTime double
function UABP_Player_C:GameThreadUpdate(DeltaTime) end
---@param DeltaTime float
function UABP_Player_C:BlueprintThreadSafeUpdateAnimation(DeltaTime) end
---@param Scale double
function UABP_Player_C:GetFootStepEffectScale(Scale) end
---@param CanSpawn boolean
function UABP_Player_C:CanSpawnFootStepEffect(CanSpawn) end
---@param CharacterSpeed double
function UABP_Player_C:GetFootStepCharacterSpeed(CharacterSpeed) end
function UABP_Player_C:StopFootStepEffect() end
function UABP_Player_C:StartFootStepEffect() end
---@param DeltaTime double
UABP_Player_C['Update Foot Step Effect'] = function(DeltaTime) end
---@param SoundId FName
function UABP_Player_C:PlaySound(SoundId) end
---@param SocketName FName
---@param ConvTF FTransform
---@param Mesh USkeletalMeshComponent
---@param IKPos FVector
function UABP_Player_C:GetRideIKPos(SocketName, ConvTF, Mesh, IKPos) end
---@param RiderComponent UPalRiderComponent
---@param ThisCharacter APalCharacter
---@param DeltaTime double
function UABP_Player_C:RiderComponent_UniqueRideUpdate(RiderComponent, ThisCharacter, DeltaTime) end
function UABP_Player_C:LookatParameterUpdate() end
---@param BagRotator FRotator
function UABP_Player_C:Cloth01FrontBagRotation(BagRotator) end
---@param ShooterComponent UPalShooterComponent
---@param WeaponNum int32
function UABP_Player_C:SerWeaponNum(ShooterComponent, WeaponNum) end
---@param PalRiderComponent UPalRiderComponent
function UABP_Player_C:RiderComponentUpdate(PalRiderComponent) end
function UABP_Player_C:PalCharacterMovementComponentUpdate() end
function UABP_Player_C:ShooterComponentUpdate() end
---@param ThisCharacter APalCharacter
---@param DeltaTime double
function UABP_Player_C:UpdateAnimationParameter(ThisCharacter, DeltaTime) end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ControlRig_3EAAD7D248100B118DCFE280A191AF83() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_7838EE814B598C3A344B9F8500E91FA4() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_9CD38A96429EBB43F9FCA4AE888E9D30() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_2BA246414BFB0071817AB1B6C2FBC83F() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_C70243AF44D929CECBC285B95A209F65() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_F8FF710E41ED5F7DA3BA9BAFE633876D() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_481DAFEA4AE40C2EFF25618E9C553B35() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_71C911754A5B3DC3A317788B75B519B1() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_996FDE544B684CDDFCA6A784C6AE9917() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_261928F6456722BEC96B86A1ADEB4BF2() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_48DAA1E9450D4A5A46AAFDAD0D2AD2B0() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_5E053D1A48F0BBA7E66B278333CAD210() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_RotationOffsetBlendSpace_A05F6A464942E6EC33FA9B8763952574() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_RotationOffsetBlendSpace_3BFF5F7E4AE63A522D3E25878E1FB093() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_137DA5324EFB47824ACFEFBEB5A9345E() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_6E057CAF466FA7A297375EB70B4C9887() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_33CE303E429A72504664588F8208C607() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_402B5DDF4A554B98804CAFBC147C07B1() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_4416090C4FED6604161B15843476CF58() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_E76C13FE4F7043059C87EA91999E16ED() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TwoBoneIK_64CC3FAB4A2F8101A3ABCDAB23163E95() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TwoBoneIK_526ABD1A42AD6ADBA987689868DF9ACB() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_E94DA2EA481166A5E285B289F1C37CBD() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_795924014DFB08AE86A92196C6243888() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_DD28266243FD9E59AD3748AABC4EC94E() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_71AACF6D4D2B261CA61871BDCE75FA8C() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_21D9D3ED464D031FBD32AAA417100B21() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_B70A311E47AEFAEE0A1D709D2E5F6D53() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_ModifyBone_3A5774CC4E383BBEFC920297F7931545() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_E26724CB458B422C7C5E32A0EDC0CCF8() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_A0D7C56C4DB9926E12DA97B72BAE7F9C() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_DE4CD99543A8127206BEFDA34A61B600() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_51630B8C43E034BBFCD4F29091E8C6E3() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_1BDF9D1447DF958038E620AEAF8B3D3D() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_F4551B3F4954505485115494503A337D() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_ED5C3EC2486FB5B5EA51D8A3B5A970C9() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_655311544FEA15E7245AB58E68400569() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_BC9B02BC4F1BA6E447E80797ACACDD6A() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_SequencePlayer_0C4BD33A4A739BB806132999D7790073() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_LayeredBoneBlend_2A54E77148A6C7AEC0F9ED9AE38259A1() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_6D1442674165687285F288812FDB1766() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_BlendListByBool_500901BD49D7425200ABDC8BE85C7F25() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_690EA54243E92C4F5F8441A6ACAD0053() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_7BFFAF7F4E48FAADBB3FC4A30EEFAC05() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_DE4B6EE04F5CA7CAF338B8AC885C2C42() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_7791845548B5FB3059EB7DABA1AC82E1() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_ADB9F44F417FA3429012D4AC0960FE81() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_819BBAD54A8DC3F5CD5532AB19D034AA() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_BAAF9A3E45024386AB704DA5C92DDA6F() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_7E971E664EA213C4A22D748CAF7084D3() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_BE56BE41476FF7AE05D9CF90C9BEB1A2() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_ACBBE620474D08C7FF2166BE65257A91() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_22357FDA45F4F504502F4D9C2B8DAC0B() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_B81AB908417297CD4DEAABAD0C247287() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_8E3C577B4AB26BF954C089A7AE5DB9F4() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_A134763D4D6875423DA3FB8416C19B47() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_1CFB42474BCF26A449A2E3960AF20DC4() end
function UABP_Player_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_AnimGraphNode_TransitionResult_B11373AF493FD1828F548C9C6DFCE1CF() end
---@param DeltaTimeX float
function UABP_Player_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UABP_Player_C:BlueprintBeginPlay() end
function UABP_Player_C:AnimNotify_Entered_StandIdle() end
function UABP_Player_C:AnimNotify_Entered_Walk() end
function UABP_Player_C:AnimNotify_Entered_Sprint() end
function UABP_Player_C:AnimNotify_Entered_Crouch() end
function UABP_Player_C:AnimNotify_Exit_Crouch() end
function UABP_Player_C:AnimNotify_OnStandIdle() end
function UABP_Player_C:AnimNotify_OnCrouch() end
function UABP_Player_C:AnimNotify_OnCrouchMove() end
function UABP_Player_C:AnimNotify_OnWalk() end
function UABP_Player_C:AnimNotify_OnExitStand() end
function UABP_Player_C:AnimNotify_Start_Climb() end
---@param EntryPoint int32
function UABP_Player_C:ExecuteUbergraph_ABP_Player(EntryPoint) end


