---@meta

---@class FAnimBlueprintGeneratedConstantData : FAnimBlueprintConstantData
---@field __NameProperty_489 FName
---@field __NameProperty_490 FName
---@field __NameProperty_491 FName
---@field __NameProperty_492 FName
---@field __NameProperty_493 FName
---@field __NameProperty_494 FName
---@field __NameProperty_495 FName
---@field __NameProperty_496 FName
---@field __NameProperty_497 FName
---@field __IntProperty_498 int32
---@field __NameProperty_499 FName
---@field __IntProperty_500 int32
---@field __NameProperty_501 FName
---@field __IntProperty_502 int32
---@field __BlendProfile_503 UBlendProfile
---@field __CurveFloat_504 UCurveFloat
---@field __EnumProperty_505 EAlphaBlendOption
---@field __EnumProperty_506 EBlendListTransitionType
---@field __ArrayProperty_507 TArray<float>
---@field __NameProperty_508 FName
---@field __IntProperty_509 int32
---@field __BoolProperty_510 boolean
---@field __FloatProperty_511 float
---@field __StructProperty_512 FInputScaleBiasClampConstants
---@field __FloatProperty_513 float
---@field __BoolProperty_514 boolean
---@field __EnumProperty_515 EAnimSyncMethod
---@field __ByteProperty_516 EAnimGroupRole::Type
---@field __NameProperty_517 FName
---@field __NameProperty_518 FName
---@field __NameProperty_519 FName
---@field __IntProperty_520 int32
---@field __StructProperty_521 FAnimNodeFunctionRef
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystem_PropertyAccess
---@field AnimBlueprintExtension_Base FAnimSubsystem_Base
FAnimBlueprintGeneratedConstantData = {}



---@class FAnimBlueprintGeneratedMutableData : FAnimBlueprintMutableData
---@field __BoolProperty boolean
---@field __BoolProperty_0 boolean
---@field __BoolProperty_1 boolean
---@field __BoolProperty_2 boolean
---@field __BoolProperty_3 boolean
---@field __BoolProperty_4 boolean
---@field __BoolProperty_5 boolean
---@field __FloatProperty_6 float
---@field __BoolProperty_7 boolean
---@field __BoolProperty_8 boolean
---@field __FloatProperty_9 float
---@field __FloatProperty_10 float
---@field __FloatProperty_11 float
FAnimBlueprintGeneratedMutableData = {}



---@class UABP_NPC_Base_C : UPalAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field __AnimBlueprintMutables FAnimBlueprintGeneratedMutableData
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystemInstance
---@field AnimBlueprintExtension_Base FAnimSubsystemInstance
---@field AnimGraphNode_Root_3 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_2 FAnimNode_LinkedInputPose
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_Fabrik FAnimNode_Fabrik
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_BlendListByBool_8 FAnimNode_BlendListByBool
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_Root_2 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_1 FAnimNode_LinkedInputPose
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_7 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_1 FAnimNode_Root
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_LinkedAnimLayer_2 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_LinkedAnimLayer_1 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_LinkedAnimLayer FAnimNode_LinkedAnimLayer
---@field K2Node_PropertyAccess_13 boolean
---@field K2Node_PropertyAccess_12 boolean
---@field K2Node_PropertyAccess_11 FRotator
---@field K2Node_PropertyAccess_10 FVector
---@field K2Node_PropertyAccess_9 FVector
---@field K2Node_PropertyAccess_8 FTransform
---@field K2Node_PropertyAccess_7 boolean
---@field K2Node_PropertyAccess_6 boolean
---@field K2Node_PropertyAccess_5 APalWeaponBase
---@field K2Node_PropertyAccess_4 boolean
---@field K2Node_PropertyAccess_3 boolean
---@field K2Node_PropertyAccess_2 boolean
---@field K2Node_PropertyAccess_1 FVector
---@field K2Node_PropertyAccess FWeaponAnimationInfo
---@field WeaponInfo FWeaponAnimationInfo
---@field VelocityXY FVector2D
---@field Speed double
---@field IsAim boolean
---@field IsReloading boolean
---@field isCrouch boolean
---@field AimRotatorForSpine FRotator
---@field IsEndJump boolean
---@field IsValidSprintAnimation boolean
---@field IsSprint boolean
---@field LeftHandTransform FTransform
---@field isAttachLeftHand boolean
---@field TSCache_ShooterComponent UPalShooterComponent
---@field TSCache_OwnerPalCharacter APalCharacter
UABP_NPC_Base_C = {}

---@param InPose FPoseLink
---@param NPC_HairClothLayer FPoseLink
function UABP_NPC_Base_C:NPC_HairClothLayer(InPose, NPC_HairClothLayer) end
---@param InPose_LeftHand FPoseLink
---@param LeftHandIK FPoseLink
function UABP_NPC_Base_C:LeftHandIK(InPose_LeftHand, LeftHandIK) end
---@param InPose FPoseLink
---@param WeaponUpper FPoseLink
function UABP_NPC_Base_C:WeaponUpper(InPose, WeaponUpper) end
---@param AnimGraph FPoseLink
function UABP_NPC_Base_C:AnimGraph(AnimGraph) end
---@param DeltaTime float
function UABP_NPC_Base_C:BlueprintThreadSafeUpdateAnimation(DeltaTime) end
---@param ShooterComponent UPalShooterComponent
function UABP_NPC_Base_C:ShooterComponentUpdate(ShooterComponent) end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_0D482E0C4B2E4E7CD091E386E53618A7() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_40C8EDE3400634534A504B80F766E208() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_3AE6580A4F970316C15CF69E11CE9615() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_BBD8BB9A4AAC9FE30FB9758FBD35CF09() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_BlendListByBool_E2DE616E480579F7354F33B1777A4358() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_BlendListByBool_F63282324F16651B07F04EA37B13D648() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_8536992D4A36125389B06C90F08A99B2() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_BlendListByBool_FA0E6E324CA7134F3022AA94B20262ED() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_BlendSpacePlayer_ECEA17A54981985346E400AE295C30FF() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_A843A5B240417E340E569DA258225C81() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_SequencePlayer_103905184AD9AADFC2AC7783DC8F943D() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_BlendListByBool_F4C92C35456A21C307270A83D6D219A6() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_98F8247B476FFB0446F91DB7328341FA() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_B09EDEC94382438CC2EA92A0E18A09D7() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_A9D4C35A4750D9C872FF0F8E72859E1D() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_F009816844CF3DF7CEFF7DAA17E020BA() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_1D93E8984AE04BDD9AC072AC8F1B4CC6() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_FB87F47D45ADB262044FA6BC9B050E13() end
function UABP_NPC_Base_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NPC_Base_AnimGraphNode_TransitionResult_41047BF041CF74296033DFA993D3480E() end
function UABP_NPC_Base_C:BlueprintBeginPlay() end
---@param EntryPoint int32
function UABP_NPC_Base_C:ExecuteUbergraph_ABP_NPC_Base(EntryPoint) end


