---@meta

---@class FAnimBlueprintGeneratedConstantData : FAnimBlueprintConstantData
---@field __NameProperty_323 FName
---@field __NameProperty_324 FName
---@field __NameProperty_325 FName
---@field __NameProperty_326 FName
---@field __NameProperty_327 FName
---@field __NameProperty_328 FName
---@field __IntProperty_329 int32
---@field __NameProperty_330 FName
---@field __IntProperty_331 int32
---@field __NameProperty_332 FName
---@field __IntProperty_333 int32
---@field __StructProperty_334 FInputScaleBiasClampConstants
---@field __FloatProperty_335 float
---@field __NameProperty_336 FName
---@field __IntProperty_337 int32
---@field __BoolProperty_338 boolean
---@field __FloatProperty_339 float
---@field __EnumProperty_340 EAnimSyncMethod
---@field __ByteProperty_341 EAnimGroupRole::Type
---@field __NameProperty_342 FName
---@field __NameProperty_343 FName
---@field __IntProperty_344 int32
---@field __BlendProfile_345 UBlendProfile
---@field __CurveFloat_346 UCurveFloat
---@field __BoolProperty_347 boolean
---@field __EnumProperty_348 EAlphaBlendOption
---@field __EnumProperty_349 EBlendListTransitionType
---@field __ArrayProperty_350 TArray<float>
---@field __StructProperty_351 FAnimNodeFunctionRef
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystem_PropertyAccess
---@field AnimBlueprintExtension_Base FAnimSubsystem_Base
FAnimBlueprintGeneratedConstantData = {}



---@class FAnimBlueprintGeneratedMutableData : FAnimBlueprintMutableData
---@field __FloatProperty float
---@field __FloatProperty_0 float
---@field __BoolProperty_1 boolean
---@field __BoolProperty_2 boolean
---@field __BoolProperty_3 boolean
---@field __FloatProperty_4 float
---@field __FloatProperty_5 float
---@field __FloatProperty_6 float
---@field __BoolProperty_7 boolean
---@field __BoolProperty_8 boolean
---@field __FloatProperty_9 float
---@field __FloatProperty_10 float
---@field __FloatProperty_11 float
---@field __FloatProperty_12 float
---@field __BoolProperty_13 boolean
---@field __FloatProperty_14 float
---@field __FloatProperty_15 float
---@field __FloatProperty_16 float
---@field __FloatProperty_17 float
---@field __ArrayProperty_18 TArray<float>
---@field __BoolProperty_19 boolean
---@field __BoolProperty_20 boolean
FAnimBlueprintGeneratedMutableData = {}



---@class UABP_MonsterBase_C : UPalAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field __AnimBlueprintMutables FAnimBlueprintGeneratedMutableData
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystemInstance
---@field AnimBlueprintExtension_Base FAnimSubsystemInstance
---@field AnimGraphNode_Root_3 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_3 FAnimNode_LinkedInputPose
---@field AnimGraphNode_LinkedInputPose_2 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_2 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose_1 FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root_1 FAnimNode_Root
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_LinkedAnimLayer_2 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_BlendSpacePlayer_7 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_6 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_7 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_5 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_LinkedAnimLayer_1 FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_LinkedAnimLayer FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field K2Node_PropertyAccess_17 UPalCharacterMovementComponent
---@field K2Node_PropertyAccess_15 boolean
---@field K2Node_PropertyAccess_14 UPalCharacterMovementComponent
---@field K2Node_PropertyAccess_12 boolean
---@field K2Node_PropertyAccess_10 float
---@field K2Node_PropertyAccess_9 float
---@field K2Node_PropertyAccess_8 FVector
---@field K2Node_PropertyAccess_7 boolean
---@field K2Node_PropertyAccess_6 FVector
---@field K2Node_PropertyAccess_4 FVector
---@field K2Node_PropertyAccess_3 FRotator
---@field K2Node_PropertyAccess_2 FWeaponAnimationInfo
---@field K2Node_PropertyAccess_1 boolean
---@field K2Node_PropertyAccess boolean
---@field __CustomProperty_AimRotator_D409488B47D1A68373AC2E9D883DDF47 FRotator
---@field __CustomProperty_LookAtWorldLocation_FBA1F7A649A7D6231954198C8C515A62 FVector
---@field IsAiming boolean
---@field IsShooting boolean
---@field WeaponAnimInfo FWeaponAnimationInfo
---@field CameraVelocityXY FVector2D
---@field AimRotator FRotator
---@field IsLookatEnable boolean
---@field LookAtTarget FVector
---@field LookatInTime double
---@field LookatOutTime double
---@field IsJumpPreliminary boolean
---@field IsSkipJumpStart boolean
---@field AngleSpeed double
---@field IsRiding boolean
---@field IsFlying boolean
---@field ShouldBeUseShooterComponent boolean
---@field ShouldBeUseRiderComponent boolean
---@field PrevMoveSpeed double
---@field FootStepEffectClass UNiagaraSystem
---@field FootStepAttachPointName FName
---@field FootStepEffect UNiagaraComponent
---@field TSCached_OwnerPalCharacter APalCharacter
---@field TSCached_ShooterComponent UPalShooterComponent
---@field TSCached_LookAtComponent UPalLookAtComponent
---@field TSCached_RideMarker UPalRideMarkerComponent
---@field IsSpawnDashEffect boolean
---@field DashEffectSpeed double
---@field IsFloating boolean
---@field MovementScale double
UABP_MonsterBase_C = {}

---@param NativePose FPoseLink
---@param ActionPose FPoseLink
---@param UpperOverride FPoseLink
function UABP_MonsterBase_C:UpperOverride(NativePose, ActionPose, UpperOverride) end
---@param InPose FPoseLink
---@param LookAtWorldLocation FVector
---@param LookAtOverride FPoseLink
function UABP_MonsterBase_C:LookAtOverride(InPose, LookAtWorldLocation, LookAtOverride) end
---@param DefaultPose FPoseLink
---@param AimRotator FRotator
---@param AimingOverride FPoseLink
function UABP_MonsterBase_C:AimingOverride(DefaultPose, AimRotator, AimingOverride) end
---@param AnimGraph FPoseLink
function UABP_MonsterBase_C:AnimGraph(AnimGraph) end
function UABP_MonsterBase_C:IsFloatingPal() end
---@param Pal APalMonsterCharacter
---@param PalSize FString
function UABP_MonsterBase_C:MakeSwitchStatePalSize(Pal, PalSize) end
function UABP_MonsterBase_C:PlayLandingSound() end
function UABP_MonsterBase_C:UpdateDashEffect_AnyThread() end
---@param DeltaTime float
function UABP_MonsterBase_C:BlueprintThreadSafeUpdateAnimation(DeltaTime) end
---@param Scale double
function UABP_MonsterBase_C:GetFootStepEffectScale(Scale) end
---@param CharacterSpeed double
function UABP_MonsterBase_C:GetFootStepCharacterSpeed(CharacterSpeed) end
---@param CanSpawn boolean
function UABP_MonsterBase_C:CanSpawnFootStepEffect(CanSpawn) end
function UABP_MonsterBase_C:StopFootStepEffect() end
function UABP_MonsterBase_C:StartFootStepEffect() end
function UABP_MonsterBase_C:PostUpdateDashEffect() end
---@param SoundId FName
function UABP_MonsterBase_C:PlaySound(SoundId) end
---@param IsSprint boolean
function UABP_MonsterBase_C:GetSprint(IsSprint) end
function UABP_MonsterBase_C:UpdateRidingParameter() end
function UABP_MonsterBase_C:UpdateBasicParameter() end
UABP_MonsterBase_C['Update Look at Parameter'] = function() end
function UABP_MonsterBase_C:UpdateShooterParameter() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ECFECB414886E0974195E991463ACD99() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_925DF20E402882570857548CCD9E3C68() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_6FEC962E4C28F1AC8D56A49C89C4ADFA() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_C95153CD4007A62F8D752891550DF5D9() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_40ADA346423143A5CAA0D4B50B157F15() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ADBAEE7E4B8D4BFED7B43DBC07178B76() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_128A52BB436E9B3A31FBB7A0A5CC15C1() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_672678E246E619FB275DE5AFE6DDA234() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_B62C4ED042628BD16274AFA4FDD16719() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_FE682B1C41C3E7BF960F52B352036D22() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_E84338B149C6CA71A04CD2A2AFEE1A26() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_FB442B974C195CB35B6129B622134627() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_EA0B5CD54E5A85E50831B98555463D29() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_CE52F1054119833750D5A6BE24F3D0CF() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F0D464AD4B31CE2D2A7A7EA95C239B70() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_EE0E56854535C9DCA7F729A194F159F1() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_A47488D6499D3064732F10A46F49E205() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_6D5D23194B5DCCF74E79899BDAC0B9BA() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_8E5298E14CFFC43AC4CB97899CB66188() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_56B64F4E4C9E82DE226407ACE61B8F62() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_94EBA2794624A1AE0E87B0B8F0C035CA() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_12D0A21548EC4F9A1B3A7F89B42E002E() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F48506EF4272DE0D9403FC8091658CC2() end
function UABP_MonsterBase_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F96787034784DF12FF90028A34BB8B39() end
---@param DeltaTimeX float
function UABP_MonsterBase_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UABP_MonsterBase_C:BlueprintBeginPlay() end
function UABP_MonsterBase_C:BlueprintPostEvaluateAnimation() end
function UABP_MonsterBase_C:AnimNotify_Landing() end
---@param EntryPoint int32
function UABP_MonsterBase_C:ExecuteUbergraph_ABP_MonsterBase(EntryPoint) end


