---@meta

---@class UWBP_OptionSettings_ListContentLRArrow_C : UUserWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Anm_Push UWidgetAnimation
---@field ArrowHover UImage
---@field Button_Dummy UButton
---@field WBP_PalCommonButton UWBP_PalCommonButton_C
---@field OnClicked FWBP_OptionSettings_ListContentLRArrow_COnClicked
UWBP_OptionSettings_ListContentLRArrow_C = {}

function UWBP_OptionSettings_ListContentLRArrow_C:ClickInternal() end
function UWBP_OptionSettings_ListContentLRArrow_C:Click() end
---@param Button UCommonButtonBase
function UWBP_OptionSettings_ListContentLRArrow_C:BndEvt__WBP_OptionSettings_ListContentLRArrow_WBP_PalCommonButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(Button) end
---@param Button UCommonButtonBase
function UWBP_OptionSettings_ListContentLRArrow_C:BndEvt__WBP_OptionSettings_ListContentLRArrow_WBP_PalCommonButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(Button) end
---@param Button UCommonButtonBase
function UWBP_OptionSettings_ListContentLRArrow_C:BndEvt__WBP_OptionSettings_ListContentLRArrow_WBP_PalCommonButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(Button) end
---@param EntryPoint int32
function UWBP_OptionSettings_ListContentLRArrow_C:ExecuteUbergraph_WBP_OptionSettings_ListContentLRArrow(EntryPoint) end
function UWBP_OptionSettings_ListContentLRArrow_C:OnClicked__DelegateSignature() end


