---@meta

---@class UWBP_CharaCre_C : UUserWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Anm_PlayerNameEdit_OffToOn UWidgetAnimation
---@field Canvas_PlayerName UCanvasPanel
---@field Image UImage
---@field Image_1 UImage
---@field Image_2 UImage
---@field Image_3 UImage
---@field Image_85 UImage
---@field Image_CautionBase UImage
---@field Image_CautionIcon UImage
---@field Image_L UImage
---@field Image_R UImage
---@field Text_PlayerName UBP_PalTextBlock_C
---@field WBP_CharaCre_MenuButton_Body UWBP_CharaCre_MenuButton_C
---@field WBP_CharaCre_MenuButton_Finish UWBP_CharaCre_MenuButton_C
---@field WBP_CharaCre_MenuButton_Hair UWBP_CharaCre_MenuButton_C
---@field WBP_CharaCre_MenuButton_Head UWBP_CharaCre_MenuButton_C
---@field WBP_CharaCre_MenuButton_Preset UWBP_CharaCre_MenuButton_C
---@field WBP_CharaCre_MenuButton_Voice UWBP_CharaCre_MenuButton_C
---@field WBP_CommonButton_65 UWBP_CommonButton_C
---@field WBP_PalCommonScrollList_Setting UWBP_PalCommonScrollList_C
---@field OnChangedTab FWBP_CharaCre_COnChangedTab
---@field ScrollBoxContentSet UWBP_CharaCre_ScrollBoxContentSet_C
---@field OnLeftRotationButtonClicked FWBP_CharaCre_COnLeftRotationButtonClicked
---@field OnRightRotationButtonClicked FWBP_CharaCre_COnRightRotationButtonClicked
---@field OnChangedSkinColor FWBP_CharaCre_COnChangedSkinColor
---@field OnChangedTorsoSize FWBP_CharaCre_COnChangedTorsoSize
---@field OnChangedLegSize FWBP_CharaCre_COnChangedLegSize
---@field OnChangedArmSize FWBP_CharaCre_COnChangedArmSize
---@field OnChangedEyeColor FWBP_CharaCre_COnChangedEyeColor
---@field OnChangedBrowColor FWBP_CharaCre_COnChangedBrowColor
---@field OnChangedHairColor FWBP_CharaCre_COnChangedHairColor
---@field OnSelectedBodyMesh FWBP_CharaCre_COnSelectedBodyMesh
---@field OnSelecteddHeadMesh FWBP_CharaCre_COnSelecteddHeadMesh
---@field OnSelectedHairMesh FWBP_CharaCre_COnSelectedHairMesh
---@field OnClickedCategoryButton FWBP_CharaCre_COnClickedCategoryButton
---@field LastClickedButton UWBP_CharaCre_MenuButton_C
---@field OnNotifyOpenSelectColorWindow FWBP_CharaCre_COnNotifyOpenSelectColorWindow
---@field OnNotifyCloseSelectColorWIndow FWBP_CharaCre_COnNotifyCloseSelectColorWIndow
---@field OnClickedEditNameButton FWBP_CharaCre_COnClickedEditNameButton
---@field OnSelectedEyeMaterial FWBP_CharaCre_COnSelectedEyeMaterial
---@field OnClickedCompleteButton FWBP_CharaCre_COnClickedCompleteButton
---@field OnSelectedPreset FWBP_CharaCre_COnSelectedPreset
---@field OnChangedVoiceID FWBP_CharaCre_COnChangedVoiceID
UWBP_CharaCre_C = {}

---@param VoiceID int32
function UWBP_CharaCre_C:RequestPlaySampleVoice(VoiceID) end
---@param VoiceID int32
function UWBP_CharaCre_C:OnSelectedVoiceID_Internal(VoiceID) end
---@param PresetName FName
function UWBP_CharaCre_C:OnSelectedPreset_Internal(PresetName) end
---@param Navigation EUINavigation
---@return UWidget
function UWBP_CharaCre_C:CustomNavi_ToCategoryTop(Navigation) end
---@param HSV FLinearColor
function UWBP_CharaCre_C:GetSelectedEyeHSV(HSV) end
---@param BindedName FName
function UWBP_CharaCre_C:OnSelectedEyeMaterial_Internal(BindedName) end
---@param isEnable boolean
function UWBP_CharaCre_C:SetEnableNameEdit(isEnable) end
---@param NewName FText
function UWBP_CharaCre_C:SetPlayerName(NewName) end
function UWBP_CharaCre_C:OnNotifyClosenSelectColorWindow_Internal() end
function UWBP_CharaCre_C:OnNotifyOpenSelectColorWindow_Internal() end
---@param Navigation EUINavigation
---@return UWidget
function UWBP_CharaCre_C:CustomNavi_ToNameChange(Navigation) end
---@param isEnable boolean
function UWBP_CharaCre_C:SetEnableSettingScrollList(isEnable) end
---@param CategoryType E_UICharacterMakeCategory::Type
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:GetCategoryButtonByCategory(CategoryType, Button) end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:OnClickedCategoryButton_Internal(Button) end
---@param CategoryType E_UICharacterMakeCategory::Type
---@param Widget UWidget
function UWBP_CharaCre_C:GetRestoreFocusTarget(CategoryType, Widget) end
---@param BindedName FName
function UWBP_CharaCre_C:OnClickedHairMesh_Internal(BindedName) end
---@param BindedName FName
function UWBP_CharaCre_C:OnClickedHeadMesh_Internal(BindedName) end
---@param BindedName FName
function UWBP_CharaCre_C:OnClickedBodyMesh_Internal(BindedName) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedHairColor_Internal(Color) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedBrowColor_Internal(Color) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedEyeColor_Internal(Color) end
---@param Value double
function UWBP_CharaCre_C:OnChangedArmSizeInternal(Value) end
---@param Value double
function UWBP_CharaCre_C:OnChangedLegSize_Internal(Value) end
---@param Value double
function UWBP_CharaCre_C:OnChangedTorsoSize_Internal(Value) end
---@param NewCategory E_UICharacterMakeCategory::Type
---@param Widget UWidget
function UWBP_CharaCre_C:GetTopFocusTarget(NewCategory, Widget) end
---@param Value float
function UWBP_CharaCre_C:OnChangedArmSize_Internal(Value) end
---@param MakeInfo FPalPlayerDataCharacterMakeInfo
function UWBP_CharaCre_C:ApplyMakeInfo(MakeInfo) end
---@param NewCategory E_UICharacterMakeCategory::Type
function UWBP_CharaCre_C:ChangeMakeCategory(NewCategory) end
function UWBP_CharaCre_C:Setup() end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedSkinColor_Internal(Color) end
---@param OldIndex int32
---@param newIndex int32
---@param FocusTargetWidget UWidget
function UWBP_CharaCre_C:OnChangedTab_Internal(OldIndex, newIndex, FocusTargetWidget) end
function UWBP_CharaCre_C:AnmEvent_NoRotation() end
function UWBP_CharaCre_C:Construct() end
function UWBP_CharaCre_C:OnInitialized() end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature(Button) end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_1_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature(Button) end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_2_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature(Button) end
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CommonButton_65_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature() end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_Finish_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature(Button) end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_Preset_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(Button) end
---@param Button UWBP_CharaCre_MenuButton_C
function UWBP_CharaCre_C:BndEvt__WBP_CharaCre_WBP_CharaCre_MenuButton_Voice_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(Button) end
---@param EntryPoint int32
function UWBP_CharaCre_C:ExecuteUbergraph_WBP_CharaCre(EntryPoint) end
---@param VoiceID int32
function UWBP_CharaCre_C:OnChangedVoiceID__DelegateSignature(VoiceID) end
---@param PresetName FName
function UWBP_CharaCre_C:OnSelectedPreset__DelegateSignature(PresetName) end
function UWBP_CharaCre_C:OnClickedCompleteButton__DelegateSignature() end
---@param EyeMaterialName FName
function UWBP_CharaCre_C:OnSelectedEyeMaterial__DelegateSignature(EyeMaterialName) end
function UWBP_CharaCre_C:OnClickedEditNameButton__DelegateSignature() end
function UWBP_CharaCre_C:OnNotifyCloseSelectColorWIndow__DelegateSignature() end
function UWBP_CharaCre_C:OnNotifyOpenSelectColorWindow__DelegateSignature() end
---@param CategoryType E_UICharacterMakeCategory::Type
function UWBP_CharaCre_C:OnClickedCategoryButton__DelegateSignature(CategoryType) end
---@param MeshPresetRowName FName
function UWBP_CharaCre_C:OnSelectedHairMesh__DelegateSignature(MeshPresetRowName) end
---@param MeshPresetRowName FName
function UWBP_CharaCre_C:OnSelecteddHeadMesh__DelegateSignature(MeshPresetRowName) end
---@param MeshPresetRowName FName
function UWBP_CharaCre_C:OnSelectedBodyMesh__DelegateSignature(MeshPresetRowName) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedHairColor__DelegateSignature(Color) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedBrowColor__DelegateSignature(Color) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedEyeColor__DelegateSignature(Color) end
---@param Size double
function UWBP_CharaCre_C:OnChangedArmSize__DelegateSignature(Size) end
---@param Size double
function UWBP_CharaCre_C:OnChangedLegSize__DelegateSignature(Size) end
---@param Size double
function UWBP_CharaCre_C:OnChangedTorsoSize__DelegateSignature(Size) end
---@param Color FLinearColor
function UWBP_CharaCre_C:OnChangedSkinColor__DelegateSignature(Color) end
function UWBP_CharaCre_C:OnRightRotationButtonClicked__DelegateSignature() end
function UWBP_CharaCre_C:OnLeftRotationButtonClicked__DelegateSignature() end
---@param TabWidget UWBP_CharaCre_Tab_C
function UWBP_CharaCre_C:OnChangedTab__DelegateSignature(TabWidget) end


